import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastProvider } from "@/components/custom/CustomToast";
import "./globals.css";
import Navbar from "@/components/home/Navbar";
import { NextAuthProvider } from "@/providers/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "w-full h-full"}>
        <NextAuthProvider>
          <ToastProvider>
            <Navbar />
            {children}
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
